### ISSUE TITLE
Please add bower.json/package.json

### ISSUE THREAD

**Issue by mbrodala** [mnater/Hyphenopoly#10]
Please add the necessary meta files to make this installable via Bower/NPM.

**Comment by mnater** [comment]
added package.json in https://github.com/mnater/Hyphenopoly/commit/bd9be262b4de7343ea0e4ce14c12fd0d7ce314b4
Hope it works.

**Comment by mbrodala** [comment]
@mnater Thanks, can you add a `bower.json` too?

**Comment by mnater** [comment]
Bower is dying:
...psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects! (https://bower.io)

**Comment by mbrodala** [comment]
Correct, the emphasis is on *new* though. ;-) Right now we are still using Bower and it works very well for us. We are not yet into Webpack but will keep an eye on it.

So unless you see a huge burden adding Bower support I'd really love to have it available as option. :-)
