### ISSUE TITLE
I figured out a way to load Hyphenopoly for browsers into Webpack 4.

### ISSUE THREAD

**Issue by julian-zatloukal** [mnater/Hyphenopoly#100]
Hello, I read the #70 and the section in the documentation regarding Webpack but I just couldn’t make it work for browsers. After a bit of testing, I finally got it to work. It’s a bit hacky but it does the work.

I created a [repository ](https://github.com/julian-zatloukal/hyphenopoly-webpack-implementation) containing all the files and code to make it load correctly, I've also designed a [simple page](https://julian-zatloukal.github.io/hyphenopoly-webpack-implementation/) to test if it works correctly.

@mnater, can I add it as an example of implementation, or add as an alternative method in the documentation?
Thanks.

**Comment by mnater** [comment]
Hi

That's awesome!
#70 and the current doc is about using the node-module within Webpack. You managed to get the combination of Hyphenopoly_Loader.js and Hyphenopoly.js to work with Webpack!

I'd really like to add your findings to the documentation. How should we proceed?
Should I link to your repo? Do you prefer to include this completely in Hyphenopoly's doc? Are you willing to make a Pull request (I'd be happy to merge)?

Thank you very much for your contribution.

Kind regards,
Mathias

**Comment by julian-zatloukal** [comment]
Great! I’ll create a new pull request adding this way of implementing Hyphenopoly in the Special use cases section of the documentation.

May I also add the files regarding this special use case into _/examples/webpack_ ?

Thanks.

**Comment by mnater** [comment]
Thank you! And yes.

BTW: I'm tinkering with your setup. Two things I think could be improved:

Hyphenopoly_Loader.js is packed in `vendor.[hash].bundle.js` and inserted at the end of the `body`. So the feature tests in Hyphenopoly_Loader are made after the body has loaded. This could cause flickering if the page becomes more demanding. I'd prefer to load Hyphenopoly_Loader.js before all other assets:
````javascript
new HtmlWebpackPlugin({
            template: './src/index.html',
            favicon: '',
            inject: 'head' //<-- add in head
        })
````
Do you know a way to selectively add assets to top/bottom in HtmlWebpackPlugin?

Use
````javascript
require: {
    es: 'anticonstitucionalmente',
     it: 'precipitevolissimevolmente',
     de: 'Silbentrennungsalgorithmus',
    'en-us': 'antidisestablishmentarianism'
},
````
to make sure the CSS-hyphens feature check works correctly.

**Comment by julian-zatloukal** [comment]
~Flickering fixed! check out my latest commits. I did also change the long words in _require._
I updated the [live version](https://julian-zatloukal.github.io/hyphenopoly-webpack-implementation/) too.~ The hyphens are not being shown now, I will figure out why.

**Comment by julian-zatloukal** [comment]
Now it's working! I've used the `html-webpack-injector` plugin. [Live version.](https://julian-zatloukal.github.io/hyphenopoly-webpack-implementation/)

**Comment by julian-zatloukal** [comment]
Pull request added, #101.
