### ISSUE TITLE
Link to example1 not found (404)

### ISSUE THREAD

**Issue by IanTrudel** [mnater/Hyphenopoly#104]
The page related to example1 provided in [README.md](https://github.com/mnater/Hyphenopoly/blob/master/README.md), https://mnater.github.io/Hyphenopoly/example1.html, does not exist.

![image](https://user-images.githubusercontent.com/8844578/77961023-386d1800-72a7-11ea-9f2a-fa424468553b.png)

**Comment by mnater** [comment]
Thank you
