### ISSUE TITLE
Cross-Origin Read Blocking (CORB) blocked cross-origin response 

### ISSUE THREAD

**Issue by csvlad** [mnater/Hyphenopoly#123]
Hello guys,

I've copied the html example code from Hyphenopoly documentation and tested it on localhost on Windows 10. 
The Hyphenopoly haven't worked and I got the following CORB warning in my console:

`Cross-Origin Read Blocking (CORB) blocked cross-origin response https://github.com/mnater/Hyphenopoly/blob/master/Hyphenopoly_Loader.js with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

How can I solve it? Thanks for your help

**Comment by mnater** [comment]
Hi

It looks like you tried to get Hyphenopoly_Loader.js from GitHub. This link serves the file with the wrong MIME (`text/html`) instead of (`application/javascript`). I think this causes the CORB error.
Please serve the files from your server or use `https://mnater.github.io/Hyphenopoly/min/Hyphenopoly_Loader.js`.

Kind regards,
Mathias

**Comment by csvlad** [comment]
Hi again! Thank you for your quick response

I've used your link but have another error:
![image](https://user-images.githubusercontent.com/52933579/81963347-a2eed300-961d-11ea-8446-9f65432eb5b3.png)

These are the scripts and styles I have in head:
```
<script>
        var Hyphenopoly = {
            require: {
                "la": "honorificabilitudinitas",
                "de": "Silbentrennungsalgorithmus",
                "en-us": "Supercalifragilisticexpialidocious"
            },
            setup: {
                selectors: {
                    ".container": {}
                }
            }
        };
</script>
<script src="https://mnater.github.io/Hyphenopoly/min/Hyphenopoly_Loader.js"></script>
<style type="text/css">
            body {
                width:60%;
                margin-left:20%;
            }
            p {
                text-align: justify;
                margin: 0 2em 0 0;
            }
            .container {
                display: flex;
                hyphens: auto;
                -ms-hyphens: auto;
                -moz-hyphens: auto;
                -webkit-hyphens: auto;
            }
</style>
```
How can I solve it? Thanks for your help

**Comment by mnater** [comment]
Well, the error messages are very clear.

Either serve everything from localhost or [set CORScredentials to omit](https://mnater.github.io/Hyphenopoly/Setup.html#corscredentials).

**Comment by csvlad** [comment]
Many thanks!

**Comment by salonidol** [comment]
js.html:9 
        
       Cross-Origin Read Blocking (CORB) blocked cross-origin response https://github.com/nobleclem/jQuery-MultiSelect with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.        my local csv file is been blocking after allowing access

**Comment by mnater** [comment]
@salonidol Sorry, I don't get what you're trying to tell me here. Could you please be more precise?

**Comment by salonidol** [comment]
@mnater I was trying to access python in javascript using python libraries so there was CORS error which i solved by giving local host to the code still i cant solve my error

**Comment by chadrackmbala** [comment]
Pourquoi ceci ? de l'aide svp !

Cross-Origin Read Blocking (CORB) blocked cross-origin response https://replit.com/@ChadrackMbala/JS with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
