### ISSUE TITLE
tools/minify.sh fails during "prepare" on WSL Debian + Github Desktop for Windows 

### ISSUE THREAD

**Issue by ReLater** [mnater/Hyphenopoly#128]
I'm using Windows Subsystem for Linux (WSL)/Debian on Windows 10.
The repositories are located on a WIN hard disc.

After cloning this repository with `Github Desktop` for Windows I started `npm i`. My goal was to get the minified JS files in directory `/min/`, too.

I get several errors:
```
volli@DELL-M6800:/mnt/z/git-kram/Hyphenopoly$ npm i

> hyphenopoly@4.5.0 prepare /mnt/z/git-kram/Hyphenopoly
> sh ./tools/minify.sh

: not foundify.sh: 3: ./tools/minify.sh:
wc: min/Hyphenopoly_Loader.js: No such file or directory
wc: min/Hyphenopoly.js: No such file or directory
: not foundify.sh: 6: ./tools/minify.sh:

.... and so on...
```

The mentioned lines (3, 6) are empty lines.

The created min directory looks like this (see small dot):
![22-05-_2020_13-43-57](https://user-images.githubusercontent.com/20780646/82667645-8fa0c080-9c38-11ea-9457-0114f46fd3c0.jpg)

Reason: Above mentioned environment forces line endings `Windows CR+LF` instead of `Linux LF` (whyever).

After forking this repository and adding a `.gitattributes` file with line https://github.com/ReLater/Hyphenopoly/blob/master/.gitattributes#L14 
and cloning that new fork all worked as expected.

Is a similiar `.gitattributes` in you repo possible?
I don' know if
`*   text eol=lf`
is too hard...

**Comment by mnater** [comment]
Sorry for my late response on this.

If it doesn‘t break compatibility on other platforms this should be done.
I‘m going to make some tests these days.
