### ISSUE TITLE
Little problem (and solution?) when Hyphenopoly_Loader.js is bundled

### ISSUE THREAD

**Issue by GiovanniSalmeri** [mnater/Hyphenopoly#135]
I stumbled upon a little problem when trying to package Hyphenopoly as an extension for [Yellow](https://github.com/datenstrom/yellow/). In this CMS, JS files are normally automatically minified and bundled. All works very well, except for line 73 in Hyphenopoly_Loader.js:

```javascript
const maindir = d.currentScript.src.slice(0, -(scriptName.length));
```

Obviously it doesn't work because scriptName is hardcoded, while currentScript.src is dynamically obtained (and in this scenario is the name of the JS bundle). It seems to me that all is trivially solved like this:

```javascript
const maindir = d.currentScript.src.substr(0, (d.currentScript.src.lastIndexOf("/")+1));
```

Am I right? Since the problem can arise in similar contexts, may I propose to modify like this the code of Hyphenopoly?

**Comment by mnater** [comment]
Absolutely!
Thanks for finding this!

**Comment by GiovanniSalmeri** [comment]
Thank you very much, with the latest commit all works perfectly!
