### ISSUE TITLE
Get param at Hyphenopoly_Loader.js breaks script

### ISSUE THREAD

**Issue by digitaldonkey** [mnater/Hyphenopoly#136]
Drupal CMS loads Javascript files often with a additional GET param (also common for cache breaking). Seems like the script does not work, in this case as it derivates the Path from the Full file name. 

Can you make it arbitrary? Like ignoring *Hyphenopoly_Loader.js?\**` when determining the path.

**Comment by mnater** [comment]
Thank you for that issue.
This will be fixed by fixing #135
