### ISSUE TITLE
Could you publish the Hyphenopoly on npmjs.com?

### ISSUE THREAD

**Issue by Matthias-Hermsdorf** [mnater/Hyphenopoly#14]
Could you publish the Hyphenopoly on npmjs.com?
It would make it easier to keep in track of package versions. Easier then check hashes.

**Comment by mnater** [comment]
I will as soon as it stabelises…

**Comment by mnater** [comment]
https://www.npmjs.com/package/hyphenopoly

**Comment by mnater** [comment]
Had to unpublish 😖
Will republish when the 24h have passed...

**Comment by mnater** [comment]
https://www.npmjs.com/package/hyphenopoly
