### ISSUE TITLE
Hyphenopoly used in Node hyphenates values in HTML attributes

### ISSUE THREAD

**Issue by jablonski** [mnater/Hyphenopoly#143]
The following example shows that Hyphenoploy used in Node.js hyphenates values in HTML-attributes (like href, breaking links in the emitted HTML). Maybe I'm doing something wrong or is it a bug?

```
console.log(
  require("hyphenopoly").config({
    sync: true,
    require: ["de"],
    defaultLanguage: "de",
    hyphen: "*",
  })(
    `<html lang="de"><body><p>Bis zu einer Bausumme von 100.000 € reichen Ihre <a href="/privat/recht-haftung/haftpflichtversicherung">Privathaftpflichtversicherung</a> bei selbst genutzten Einfamilienhäusern.</p></body></html>`
  )
)
```

```
<html lang="de"><body><p>Bis zu einer Bau*sum*me von 100.000 € rei*chen Ihre <a href="/pri*vat/recht-​haftung/haft*pflicht*ver*si*che*rung">Pri*vat*haft*pflicht*ver*si*che*rung</a> bei selbst ge*nutz*ten Ein*fa*mi*li*en*häu*sern.</p></body></html>
```

**Comment by mnater** [comment]
The node module expects normal text as input, not html.
I decided to not include the functionality to hyphenate html in node. I don‘t see a use case for this. (Convince me;-)

**Comment by jablonski** [comment]
Thanks for the reply, I wasn't aware about this difference.

Our use case is a static site (generated via Gatsby) powered by a headless CMS. We want to build a site which renders blazing fast and which is as small as possible, so our approach was to use Hyphonopoly to hyphenate all texts in the build run. Unfortunately we have to process some HTML blocks (think of a Wyswiyg-Editor used in CMS) besides lots of plain text. This approach works very well besides the above mentioned links and so on.

**Comment by mnater** [comment]
Hm, I see.
The danger with this approach is that we don‘t know how search engine crawlers will handle the soft hyphens. So I would statically serve the Hyphenopoly_Loader so that the page is fast for all UAs supporting CSS-Hyphenation and a bit slower for the others.
But that‘s up to you to decide.
I‘ll see what I can do in the next few days to include a HTML-Hyphenator in the node module.

**Comment by mnater** [comment]
Just to make sure: The things you want to add hyphenation to are strings with html tags and not DOM-nodes. Correct?

**Comment by jablonski** [comment]
Yes, just strings with HTML tags included.

**Comment by jablonski** [comment]
With the knowledge that Hyphenopoly does only hyphenate plain text when used in Node, we can simply build a workaround with a HTML parser (like JSDOM) and feed just the text nodes to Hyphenopoly. So maybe adding some "warning" in the documentation would be enough, so other people won't run into the same trap.

But if it is no big deal to provide HTML hyphenation on server side, I would really appreciate your effort.

For documentation purposes I've attached an example below.

```
const { JSDOM } = require("jsdom")

const hyphenator = require("hyphenopoly").config({
  sync: true,
  require: ["de"],
  defaultLanguage: "de",
  minWordLength: 6,
  leftmin: 4,
  rightmin: 4,
})

function hyphenateText(text) {
  if (typeof text === "string") {
    return hyphenator(text)
  } else {
    return undefined
  }
}

function hyphenateHtml(html) {
  if (typeof html === "string") {
    if (html.trim().startsWith("<")) {
      const fragment = JSDOM.fragment(html)
      const hyphenateNode = (node) => {
        for (node = node.firstChild; node; node = node.nextSibling) {
          if (node.nodeType == 3) {
            node.textContent = hyphenator(node.textContent)
          } else {
            hyphenateNode(node)
          }
        }
      }
      hyphenateNode(fragment)
      return fragment.firstChild["outerHTML"]
    } else {
      return hyphenator(html)
    }
  } else {
    return undefined
  }
}

module.exports = { text: hyphenateText, html: hyphenateHtml }

```

**Comment by mnater** [comment]
Hi

Thanks for your last answer.
Actually the only way to separate HTML strings is to send them through a parser first. To introduce a dependency on a parser in Hyphenopoly goes too far in my opinion. It would go beyond the scope of the script and in your use case you probably already have a parser for checking the HTML code.

So I have to leave it at a note in the documentation.

May I use your sample code and name you as a contributor?

**Comment by jablonski** [comment]
Yes, of course. And thank you very much for your effort putting into Hyphenopoly.

**Comment by axkibe** [comment]
Google has no issues indexing my page that has "\&shy;" hyphens preset.

Thanks @jablonski I applied a similar hack as well to get it working, being surprised it only does plain strings destroying links.

Really would support getting this functionality in the block. (Personally I don't quite see why one should offload this to runtime computation with javascript in the browser)
