### ISSUE TITLE
re-render functions?

### ISSUE THREAD

**Issue by ESEEG** [mnater/Hyphenopoly#144]
I've got three inputfields which I (onclick) cumulate into one div-container. This container uses hyphenopoly. 
So far using Firefox everything is working fine but not in Chrome.
I assume it doesn't work because the targeted text doesn't exist (yet) when the page is loaded. Is there any callback/render function I can call if the div-container has been filled?

**Comment by mnater** [comment]
https://mnater.github.io/Hyphenopoly/Hyphenators.html

is this what you are looking for?

BTW: it probably works in FF but not in Chrome because FF supports native CSS-hyphenation.

**Comment by ESEEG** [comment]
`Hyphenopoly.hyphenators.HTML.then((hyn) => {
  hyn(document.getElementById("hyphenateme"));
});`
it is! Thank you!
