### ISSUE TITLE
Catch more errors

### ISSUE THREAD

**Issue by mnater** [mnater/Hyphenopoly#15]
Currently no errors are catched nor handled.
- [x] add error handling for dangerous things (specifically: ressource loading, DOM manipulations)
- [x] see if an error event could be better than the error function in setup

**Comment by mnater** [comment]
Thinking about defining a set of CustomEvents and Errors:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events

**Comment by mnater** [comment]
Fixed in https://github.com/mnater/Hyphenopoly/commit/20a750514a9c39c667138b15d6c9d7ee29494563

Documentation:
https://github.com/mnater/Hyphenopoly/wiki/Events

Todo:
- [x] define which errors should be handled by Hyphenopoly
- [x] catch more errors

**Comment by FrankConijn** [comment]
Is there a way to correct hyphenation errors of certain words at system level? If so, could you include a How To?
