### ISSUE TITLE
Contra documentation, exceptions are case-sensitive

### ISSUE THREAD

**Issue by dfoxfranke** [mnater/Hyphenopoly#157]
The Hyphenopoly documentation claims that hyphenation exceptions are not case-sensitive, but this appears to be untrue. I put this stanza into my Hyphenopoly config:

```json
"setup": {
    "exceptions": {
        "en-us": "quadrant-opaque"
    }
}
```
But that didn't prevent the capitalized form from getting hyphenated as "Quadran-topaque". If I explicitly include the capitalized form "Quadrant-opaque" in my exception list, then it works correctly.

**Comment by mnater** [comment]
Hi

Thanks for reporting. Exceptions must be case-sensitive (for cases like strei-ken-de vs Streik-en-de in german).

Where are exceptions being documented as not case-sensitive?

Best regards,
Mathias

**Comment by mnater** [comment]
Ah, just found it. Thank you!
