### ISSUE TITLE
Please explain: are pattern format and license libre/MIT?

### ISSUE THREAD

**Issue by graphicore** [mnater/Hyphenopoly#164]
From the project README (emphasize mine):

> Hyphenopoly.js uses *a **proprietary** binary format* (including pattern license, metadata and the patterns)

But I can't find more information about the nature of that. Especially the word "proprietary" is often used to describe "not libre", I know it can mean other things, like *"a **custom** binary format"*, but in this context it is important to know exactly how it is meant. Thus, the question is:

Are the pattern licenses different from the MIT license of this project. If so, what are the terms of these pattern licenses, and where can I find them?

Licenses are in my case important for compliance, this would be a main factor if I can or can not use the project, which, by the way, looks amazing!

**Comment by mnater** [comment]
Thanks for asking. The text in the readme is a bit outdated.

The hyphenation patterns are supplied along with the hyphenation core functions in the language-specific web assembly file. The program code in the web assembly file comes from me and is licensed under the MIT license. The hyphenation patterns come from other authors and are under various (FOSS) licenses (mainly LPPL and MIT, some GPL) and converted to a proprietary (a custom binary) format by me. 
You can check the license of the respective patterns in the .wasm file or on https://github.com/hyphenation/tex-hyphen.

**Comment by graphicore** [comment]
Awesome, thanks for answering!
