### ISSUE TITLE
hyphenation for Greek

### ISSUE THREAD

**Issue by antonis-tsolomitis** [mnater/Hyphenopoly#168]
I am trying to use this project for hyphenation for Greek (since Firefox does not support css hyphenation for Greek yet) but it seems that it does not work. Eg.
[https://pythagoras.samos.aegean.gr/node_modules/hyphenopoly/examples/example.html](https://pythagoras.samos.aegean.gr/node_modules/hyphenopoly/examples/example.html)

The other 3 languages get hyphenated but not Greek. However the file is modified with a Greek paragraph in an identical way to the other three languages. (FORCEHYPHENOPOLY or a long word does not make any difference) (FF is version 89.0.2)

**Comment by mnater** [comment]
I get the follwoing error on the page you linked:
`Loading failed for the <script> with source “https://pythagoras.samos.aegean.gr/node_modules/hyphenopoly/examples/Hyphenopoly_Loader.js”.`

Please make sure the scripts can be loaded.
The other languages are hyphenated natively by CSS-hyphens.

**Comment by antonis-tsolomitis** [comment]
You are right. I am sorry. My bad.
