### ISSUE TITLE
Trigger hyphenation after AJAX content update?

### ISSUE THREAD

**Issue by jhuhta** [mnater/Hyphenopoly#17]
I'm getting new content to a page with an AJAX request. The hyphenation works fine when the page is first loaded, but after ajax refresh no hyphenation is happening. 

What is the recommended way to make Hyphenopoly to do it again? Not sure if this is a FAQ, but maybe have it documented as well.

**Comment by mnater** [comment]
There's no way, yet. I honestly completely forgot this use case, but I think it's pretty important.

For the moment I see two ways to implement this:

1. Register [MutationObservers](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) on the elements treated by Hyphenopoly. A mutation of the element could then trigger hyphenation.
\+ no further action by the user of the script required
\- will not necessarily trigger on new elements (need to check this)

2. Expose a public hyphenate-Function (like [Hyphenator](https://github.com/mnater/Hyphenator/blob/wiki/en_PublicAPI.md#mixed-hyphenatorhyphenatemixed-target-string-lang) does). The user of the script could call this function to hyphenate elements.
\+ fine grained control on what is hyphenated (new elements); could also be used in other cases.
\- further action by the user of the script required

Other ideas?

I could also think of implementing both.

**Comment by mnater** [comment]
As of commit https://github.com/mnater/Hyphenopoly/commit/dcb490d4487dd00ec5fa8d1fcfc2a186fc6c9b3d a document can now be hyphenated by dispatching the `contentLoaded`-event: https://github.com/mnater/Hyphenopoly/wiki/Events#contentloaded-event

I'll drop the idea with MutationObservers. It would be very hard to filter all mutations (Hyphenopoly itself triggers lots of them) and not creating an infinite loop.

**Comment by jhuhta** [comment]
Thank you! Works like a charm.

**Comment by vielhuber** [comment]
This is how to dispatch the event:
`Hyphenopoly.events.dispatch('contentLoaded');`

**Comment by mnater** [comment]
Thanks for clarification.
I'd recommend to use [Hyphenators](https://github.com/mnater/Hyphenopoly/wiki/Hyphenators) to prevent a costly rehyphenation of the whole document.
