### ISSUE TITLE
Wrong hyphen characters on MacOs with chromium browsers

### ISSUE THREAD

**Issue by ReLater** [mnater/Hyphenopoly#177]
I just want to report this issue here because I have no possibilities to test it (I have no Mac or so).

- Hyphenopoly 4.12.0.
- Maybe you have possibilities to test this or other users read this and are willing to go deeper into this issue and have time to test it with their hyphenopoly implementations.
- For Joomla we have developed a free Plugin that inserts Hyphenopoly in Joomla pages. It works without any issues for years now.
- - In short: It adds `.hyphenate` and `.donthyphenate` classes to configured selectors before hyphenopoly gets loaded. Adds a CSS script for `hyphens` for browsers that don't need Hyphenopoly. Adds the Hyphenopoly scripts and configuration and lets them do their job.

- In the last 2 weeks I got two reports that chromium browsers (Brave and Chrome) on MacOs displays strange characters instead of hyphens in the frontend (see image please).
- The users report that only chromium browsers are affected.
- I, personally, don't think that it's a hyphenopoly issue but an issue of the "strange MacOs browser engines hell".

Thank you!

![grafik](https://user-images.githubusercontent.com/20780646/149311757-9abc968d-c84c-4936-8dd8-24fc922f334e.png)

A typical configuration block that the plugin sets for de-de:

```
// Early script that implements a addClass function for .hyphenate and .donthyphenate classes.
<script src="/media/plg_system_hyphenateghsvs/js/hyphenateghsvsVanilla.js?1642069734"></script>

// Adds classes to configured selectors
document.addEventListener("DOMContentLoaded", function(){
 var selectors = new Hyphenateghsvs(".div4hyphens");
 selectors.addClass("hyphenate");
 var selectors = new Hyphenateghsvs(".icons, code, .code-filename");
 selectors.addClass("donthyphenate");});

// Later
	<style>.hyphenate{word-wrap:break-word;-webkit-hyphens:auto;-moz-hyphens:auto;-ms-hyphens:auto;-o-hyphens:auto;hyphens:auto}.donthyphenate{word-wrap:break-word;-webkit-hyphens:none;-moz-hyphens:none;-ms-hyphens:none;-o-hyphens:none;hyphens:none}</style>

	<script>;var Hyphenopoly = {
    "require": {
        "de-de": "Silbentrennungsalgorithmus"
    },
    "fallbacks": {
        "de-de": "de"
    },
    "paths": {
        "patterndir": "/media/plg_system_hyphenateghsvs/js/hyphenopoly/patterns/",
        "maindir": "/media/plg_system_hyphenateghsvs/js/hyphenopoly/"
    },
    "handleEvent": {
        "error": function (e) {e.preventDefault();}
    },
    "setup": {
        "hide": "element"
    }
};</script><script src="/media/plg_system_hyphenateghsvs/js/hyphenopoly/Hyphenopoly_Loader.js"></script>
```

"handleEvent" and "hide" are variable.

One user has also tested with "FORCEHYPHENOPOLY".

Other user never has answered on my questions

**Comment by mnater** [comment]
Hi

This looks like an issue with the font. Some webfonts don‘t support the complete charset. The soft hyphen witch Hyphenopoly inserts is often among those unsupported charcters.

I believe some browsers fall back to other fonts for unsupported chars.

Do you know the font used in the example? I‘d like to investigate this issue (I have a Mac).

**Comment by ReLater** [comment]
On the page where the image above is from:

`font-family: Hind;`

No fallback font in CSS as far as I see.
Included via fonts.gstatic.com.

On the other page

`font-family: 'Roboto';`

No fallback font in CSS for the relevant areas as far as I see.
Included via fonts.gstatic.com.

**Comment by mnater** [comment]
Those fonts support the soft hyphen.
Just googled this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1267606

I can't do anything but wait for Feb 01 2022.

**Comment by ReLater** [comment]
Thank you for investigations! I found a lot but not that issue.
Let's see.

**Comment by ReLater** [comment]
Nur zur Info. Ich habe gerade Nachricht erhalten:

> Habe eben ein CHROME Update auf meinem MacBook gemacht, jetzt geht es auch mit dem "-".
