### ISSUE TITLE
Example Code

### ISSUE THREAD

**Issue by witoldwegner** [mnater/Hyphenopoly#183]
Good day,

aren't there two lines swapped in the example-code?

Shouldn't be
`<title>Example 1</title>
        <script>
        <script src="./Hyphenopoly_Loader.js"></script>
          Hyphenopoly.config({
        `

like this?'
`<title>Example 1</title>
        <script src="./Hyphenopoly_Loader.js"></script>
        <script>
          Hyphenopoly.config({
`

Cheers,
Witold

**Comment by mnater** [comment]
Yes, absolutely.
Thank you!
