### ISSUE TITLE
All files in Hyphenopoly folder plus path modification

### ISSUE THREAD

**Issue by FrankConijn** [mnater/Hyphenopoly#19]
I put the Hyphenopoly files in a separate folder with the same name and put the folder in the root.  But that produced 404 errors. Still, that is where I need them to be,  and I'd think many more people do. Could you modify the package and paths as such?  It would speed up the implementation of your system substantially.

**Comment by mnater** [comment]
Paths are configurable: https://github.com/mnater/Hyphenopoly/wiki/Global-Hyphenopoly-Object#paths

**Comment by FrankConijn** [comment]
I know they are. But if I were you, I'd focus on user-friendliness. With Chrome on Windows being the last browser to implement native CSS hyphenation (on newer Android devices it already does), that would be the only 'raison d'être' for your system, I'd think.

**Comment by mnater** [comment]
Obviously I didn't understand your initial reques correctly, sorry.

You apply for a change of the default paths to represent the following structure:
````
root/
├── Hyphenopoly
│   ├── Hyphenopoly.js
│   ├── Hyphenopoly_Loader.js
│   ├── hyphenEngine.asm.js
│   ├── hyphenEngine.wasm
│   └── patterns
│       ├── de.hpb
│       ├── en-gb.hpb
│       ├── en-us.hpb
│       ├── nl.hpb
│       └── [...]
├── index.html
└── [...]
````
Correct?
That seems logical to me, too

**Comment by FrankConijn** [comment]
Yep, that's what I mean. :-)

**Comment by FrankConijn** [comment]
I see you updated a number of files, so I assume you implemented the suggestion. Thanx. But shouldn't the README also be updated? It now still reads: 
`<script src="./Hyphenopoly_Loader.js"></script>`

Assuming your example file is at the same level, in the root, shouldn't it read: 
`<script src="Hyphenopoly_Loader.js"></script>`?

**Comment by mnater** [comment]
No, that's correct. The Readme reflects the layout in the repository and `./Hyphenopoly_Loader.js` and `Hyphenopoly_Loader.js` points to the same file.

**Comment by FrankConijn** [comment]
Not on a(n older) local XAMPP server. I don't know about WAMPP or newer XAMPPs, but on older XAMPPs the file path `/Hyphenopoly_Loader.js` results in a 404: `Loading failed for the <script> with source “http://localhost/Hyphenopoly_Loader.js”`. No matter where the script-searching file is at. (Older?) XAMPPs have different relative-root rules. And you know what they say about the first impression.
