### ISSUE TITLE
It doesn't work with Italian (maybe?)

### ISSUE THREAD

**Issue by WhiteTiger-IT** [mnater/Hyphenopoly#203]
I have installed and activated the plugin in Joomla 4.
Also I added in the plugin the IT language, it-IT and the word "novecentonovantesimo".
Fully-justified paginated text does not appear with hyphenation.
Tried on a Win10 PC in Chrome and Opera.
On Android with Chrome and Firefox.
Am I doing something wrong?

**Comment by mnater** [comment]
Hi
This is not the repository of the Joomla plugin but rather the repo of the library used by the plugin (hyphenopoly).
Italian works fine here, so it's probably an issue with the plugin? You should post your issue there.
(Probably https://github.com/GHSVS-de/plg_system_hyphenateghsvs)
But feel free to reopen, when it's indeed a issue with hyphenopoly.
Kind regards.

**Comment by ReLater** [comment]
Question has been answered here: https://github.com/GHSVS-de/plg_system_hyphenateghsvs/issues/53
