### ISSUE TITLE
Beta versions should not be the latest official version with package managers

### ISSUE THREAD

**Issue by peter-neumann-dev** [mnater/Hyphenopoly#204]
When using a package manager (in my case NPM) the beta versions are always suggested as the official latest. Shouldn't there only appear official releases that are safe to use, so no alpha, beta or pre-release versions?

<img width="851" alt="Peter Neumann 2023-07-21 at 16 40 56@2x" src="https://github.com/mnater/Hyphenopoly/assets/75690659/54c3c4c5-a8fc-4992-b473-bd947e7e6fbe">

And I wanted to mention: Thank you for this awesome work with this polyfill 👌 … using it in every project!

**Comment by mnater** [comment]
Thanks!
Tagged v5.1.0 as "latest" and hopefully won't forget to tag future betas correctly.
