### ISSUE TITLE
Provide Hyphenopoly module path to loader() / loaderSync()?

### ISSUE THREAD

**Issue by danburzo** [mnater/Hyphenopoly#207]
Since Hyphenopoly [requires an explicit `loader` / `loaderSync` function](https://github.com/mnater/Hyphenopoly/commit/ec563f043b8184381dcd0804f80f4bbc69e092e0) in Node and other non-browser JS runtimes, it would be great if these functions received Hyphenopoly’s module URL as a second argument, to make it easier to locate the `patterns` folder. 

For example, percollate, which uses Hyphenopoly for hyphenation, can be run either as a standalone CLI or a Node.js dependency. As [I’ve just been reminded](https://github.com/danburzo/percollate/issues/163), only the former has `node_modules/hyphenopoly/patterns`. 

Getting `import.meta.url` as the second argument to the `loader()` / `loaderSync()` functions — or, even better, maybe something like `new URL('./patterns', import.meta.url)` —  would help us prevent things like [`createRequire()` to locate the patterns folder](https://github.com/yashha/percollate/commit/12e7ca817a5ef814f06fae3b33c0c211270f0c89):

```js
// before
loaderSync: file => {
  return readFileSync(
    createRequire(import.meta.url).resolve(`hyphenopoly/patterns/${file}`)
  );
}

// after
loaderSync: (file, patternsFolder) => {
   return readFileSync(new URL(`./${file}`, patternsFolder));
}
```

cc @yashha

**Comment by mnater** [comment]
Thanks for pointing to this. It makes the loaders a lot simpler indeed.
