### ISSUE TITLE
Make FOUHC prevention optional

### ISSUE THREAD

**Issue by etenzy** [mnater/Hyphenopoly#27]
Sometimes it's annoying when the text "flashes".

An option like "hideOnHyphenate" (even if defaults to true) would be a nice thing in my opinion.

**Comment by mnater** [comment]
Hi

Hyphenopoly_Loader.js should hide the content of the whole document before it is rendered, thus, actually, there should be no "flashing" at all.

Could you please elaborate where the flashing occurs? (site, browser versions etc.)

But I agree that the hiding is somewhat dangerous and should be optional, though.

Thanks, Mathias

PS: Wir können von mir aus auch auf Deutsch diskutieren.

**Comment by mnater** [comment]
For the record:
Disabling the hiding could have some perf impact specially on paint intensive pages:
![donthide](https://user-images.githubusercontent.com/280635/42060094-faf70e56-7b25-11e8-9f41-a6455650bec3.png)

Whereas with hiding enabled we get better page performance:
![hide](https://user-images.githubusercontent.com/280635/42060207-5dc72b7e-7b26-11e8-86ee-155795bc232b.png)

(measured on chrome 67)

**Comment by etenzy** [comment]
my bad... 
i've put the loader into the footer, to the rest of my js.
putting the loader in the header fixed it.

**Comment by mnater** [comment]
😇
Since the perf is really bad and text that suddenly hyphenates looks ugly I decided to not make any changes.
