### ISSUE TITLE
Template strings not supported by IE/Safari

### ISSUE THREAD

**Issue by webber-ch** [mnater/Hyphenopoly#28]
The back ticks (`) or template strings in Hyphenopoly_Loader.js on line 193 and line 398 are not working in Internet Explorer and Safari. Please use instead of template strings the concatenating of strings and variables. More information about template strings and support here: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/template_strings

**Comment by mnater** [comment]
The german mdn-page is outdated:
Safari supports template strings since version 9.1

But IE11 is still an argument…

**Comment by mnater** [comment]
Fixed in 
https://github.com/mnater/Hyphenopoly/commit/740e2a293c7a27a770fb1a276282ce38bb87b1d9
and
https://github.com/mnater/Hyphenopoly/commit/a894010a8926f6700571ad939e0bfc7caaa55a6d

**Comment by webber-ch** [comment]
Thanks a lot!
