### ISSUE TITLE
contentEditable is possible?

### ISSUE THREAD

**Issue by andremacola** [mnater/Hyphenopoly#30]
Is it possible tu use this polyfill with contentEditable elements? I would like to edit and visualize in real time.

**Comment by mnater** [comment]
Possible – yes. Try this for a start:

````javascript
document.getElementById("editor").addEventListener("blur", function() {
    if (Hyphenopoly) {
        Hyphenopoly.events.dispatch("contentLoaded");
    }
}, false);
````

At least Hyphenopoly is fast enough to instantaneously display hyphenated text :-)

But there are some issues:

1. It won't work properly with events that fire after each edit (`keypress`, `input`). Hyphenopoly replaces the elements text with hyphenated text and that makes the cursor jump to the beginning.
Whereas with CSS-hyphenation words get hyphenated if a space is written, making hyphenation much more 'live'.
2. Hyphenopoly inserts soft hyphen all over the text. So reediting becomes quite cumbersome and text scattered with soft hyphens will go to your DB. So make sure to remove all soft hyphens when entering contendEditable-mode and before saving the text.

Hope this helps…
Best regards,
Mathias

**Comment by andremacola** [comment]
Thanks. I think I can make it work.

**Comment by andremacola** [comment]
Thks. I think I can make it work.
