### ISSUE TITLE
Maximum word length problem

### ISSUE THREAD

**Issue by limpbizkit107** [mnater/Hyphenopoly#33]
Hi,
 I have face a problem with the maximum length of the words that can be hyphenated.

 **For example** I have initialize German language and trying to hyphenate word : **"Kindercarnavalsoptochtvoorbereidingswerkzaamhedenplan"** ->**"Kin-der-car-na-vals-op-tocht-vo-or-berei-dings-werk-zaam-he-den"**

 **Problem**:  The last 4 symbols are missing which happen on other languages too.

 Is there any limitation by word length or this is some bug ?
 Could you suggest workaround or some fix for current situation?

 Regards,
 Stefan

**Comment by mnater** [comment]
Yes, there is a maximum length of 61 characters.
Your example has a length of 53 characters, so this is a bug.

Thanks for reporting.
