### ISSUE TITLE
Hyphenate one word

### ISSUE THREAD

**Issue by vin-ni** [mnater/Hyphenopoly#37]
Ist there a way to call Hyphenopoly with one word to get returned an array with all possible linebreaks?

I need to just know where a word could break.

Thanks!

**Comment by mnater** [comment]
Hi

Not directly. But you can just hyphenate one word (see [hyphenators](https://github.com/mnater/Hyphenopoly/wiki/Hyphenators#use-hyphenopolyhyphenators-for-strings)) and than use [`Sting.prototype.split`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split) to get the array.
