### ISSUE TITLE
On Load site is blinking

### ISSUE THREAD

**Issue by croban** [mnater/Hyphenopoly#40]
I don't know why but the whole site is hidden on Load and after is shown. This lead to site blinking while navigating through the site

**Comment by mnater** [comment]
Possibly a duplicate of https://github.com/mnater/Hyphenopoly/issues/27

Please provide some more information: e.g. a link where I can see and reproduce the issue.

**Comment by croban** [comment]
Can you give me your email. I would not like to put here the link of the site

**Comment by mnater** [comment]
mathiasnater at gmail dot com

Deutsch passt auch ;-)

**Comment by mnater** [comment]
Hi

Jetzt konnte ich das Problem nachvollziehen.
Interessanterweise ist es in Chrome und Safari weniger augenscheinlich als in Firefox (alles auf macOS, IE habe ich jetzt noch nicht getestet).

Hintergrund:
Falls Silbentrennung auch Hyphenopoly gemacht werden soll, setzt Hyphenopoly_Loader.js die visibility des body-Elements vorübergehend auf 'hidden‘. Das hat zwei Gründe:
1. So wird verhindert, dass der Text bei der Silbentrennung rumspringt.
2. Performance: alles in allem wird so schneller Inhalt angezeigt, weil nur ein ' paint‘ gemacht wird und nicht mehrere.
Wenn die Silbentrennung funktioniert hat, wird der body wieder sichtbar gemacht. Im Fehlerfall setzt ein timeout ein, dass den body wieder sichtbar macht (per default nach 1000ms).

Problem:
Auf der Performance-Analyse in Chrome sieht man, dass Hyphenopoly_Loader.js das Nachladen der anderen Ressourcen sehr schnell anstösst, das Hyphenator.js-Skript aber mit einer grossen Verzögerung geladen wird (vorher werden diverse Header-Bilder geladen). Das hat zur Folge, dass die Silbentrennung entsprechend spät gemacht wird oder das FOUC-timeout anspringt und die Seite solange hidden bleibt.
Mit den grossen Header-Bildern ist das besonders gut sichtbar.

[…]

Ich werde versuchen, ein vereinfachtes Testcase zusammenzubauen und kucken, was sich auf Seite Hyphenopoly machen lässt…

Beste Grüsse,
Mathias

**Comment by dirkhe** [comment]
Ich habe das dasselbe Problem, lade den loader aber async per JS nach. Vorher würde es bei mir aber auch keinen Sinn machen, weil die css-klasse auch nachträglich an die Elemente geschrieben werden (dynamischer content)
Vlt. macht es Sinn, im Loader anzufragen, ob das document schon geladen ist oder dass man in der config angeben kann, dass es nachträglich geladen wurde.
Das Setzten der Visibility auf hidden arbeitet natürlich auch gegen den Browser, wenn der versucht die Seite zu analysieren, um sie schnell darzustellen. Natürlich kann ich die oben beschriebenen Gründe nachvollziehen, aber ich denke das kommt echt auf die Seite an, bzw. deren Inhalt an. Daher könnte ich mir das mit der config ganz gut vorstellen.

Gruss
Dirk

**Comment by mnater** [comment]
Hi Dirk

Der Loader braucht noch kein document.body und er braucht dementsprechend auch noch keine css-klassen. Der Loader macht Feature-Tests: Wird CSS hyphens unterstützt? Für die in require angegebenen Sprachen? Wird Webassembly unterstützt?) und startet dann je nach Ergebnis das Nachladen der anderen Ressourcen. Für die Tests erstellt der Loader einen fake-body und löscht diesen dann wieder.
Der Loader registriert auch einen Handler auf den DOMContentLoaded-Event der dann die Silbentrennung durch Hyphenopoly auslöst (sobald geladen).

Es macht IMO also durchaus Sinn und ich empfehle es sehr, den Loader statisch zu laden und zwar so früh wie möglich.

Wenn CSS-Klassen nachträglich eingefügt werden, empfehle ich https://github.com/mnater/Hyphenopoly/wiki/Events#contentloaded-event zu verwenden um die Silbentrennung anzustossen.

AFAIK können die Browser den Content auch analysieren, wenn er hidden ist (anders wäre das bei display:none). Wenn du genaueres weisst, bin ich sehr interessiert.

Beste Grüsse,
Mathias

**Comment by dirkhe** [comment]
Hi Matthias,

Danke für dein Feedback. 
Das Problem ist ja, da er beim Initialisieren (run) des loaders den body auf hidden setzt und zwar nach dem Testen(featureTestCSSHyphenation). Das Trennen macht er dann in der Tat nach dem der content geladen ist, aber dann setzt er ja erst den body wieder auf visible. 
Vlt. macht es ja Sinn, das "hidden setzten" an das "elementsReady" event zu hängen und zwar nur, wenn er Elemente gefunden hat? Oder kommt es dann auf jeden Fall zum flackern?

Dann wäre vlt. doch die Lösung per config gut. Ich habe das bei mir mal ausprobiert, dass ich das hidden auskommentiere, dann sieht es bei mir gut aus.

gruss
Dirk

**Comment by mnater** [comment]
Notes:

__Current behaviour:__
Hyphenopoly_Loader sets `visibility` of `documentElement` to `hidden`.
Hyphenopoly sets `visibility` of `documentElement` to `visible`.
__Pros:__
+ single paint
+ Simplicity

__Cons:__
- whole page flickers when navigating

__Recommended for:__
- single page sites
- pages with no static layout elements
----
__Option2 (no hiding):__
__Pros:__
+ No flickering of elements that are not handled by Hyphenopoly
+ Simplicity

__Cons:__
- hyphenated text jumps.
- two paints

__Recommended for:__
- pages where text is below the fold
----
__Option3 (hide hyphenated elements):__
`onDOMContentLoaded` Hyphenopoly_Loader sets `visibility` of `document.querySelectorAll(<elementSelectors>)` to `hidden` (and stores the original state).
When Hyphenopoly is done with an element it resets its `visibility` to the original state.
__Pros:__
+ only parts of the page flickers
+ no jumping text

__Cons:__
- value of visibility before hiding must be stored for each element (`getComputedStyle` -> slow).
- hyphenated elements flickers (specially if there's a background).

__Recommended for:__
- pages where text doesn't have a different background-colour.
- small number of hyphenated elements.
----
__Option4 (hide hyphenated texts):__
`onDOMContentLoaded` Hyphenopoly_Loader sets `color` of `document.querySelectorAll(<elementSelectors>)` to `transparent` (and stores the original state).
When Hyphenopoly is done with an element it resets its `color` to the original state.

__Pros:__
+ only text flickers (background still visible).
+ no jumping text.

__Cons:__
- value of color before hiding must be stored for each element (`getComputedStyle` -> slow).

__Recommended for:__
- pages where text has its own background.
- small number of hyphenated elements.
----

In any case:
- make behaviour configurable (let the user decide what's best for her page)
- implement https://github.com/mnater/Hyphenopoly/issues/42 first
- remove style attributes set by Hyphenopoly from HTML when done
