### ISSUE TITLE
Fallback-Definition for lang-Attrs

### ISSUE THREAD

**Issue by OktarinTentakel** [mnater/Hyphenopoly#41]
Hi there,

this is a great package, thank you for all the work you put in, this is a very mature and flexible solution for a complicated problem and everything so far works fine.

Except this one thing of course :D

https://github.com/mnater/Hyphenopoly/wiki/Global-Hyphenopoly-Object#fallbacks

If I'm trying to define fallbacks to map lang-Attr values to specific dictionaries I seem to be out of luck.

Example: I'm setting lang="de-CH" on html or another element and define a fallback "de-CH" : "de" in the Hyphenopoly config.

In that case he's loading the correct dict, but giving me the "Hyphenopoly_Loader.js:105 Element with 'de-ch' found, but 'de-ch.hpb' not loaded. Check language tags!" exception nonetheless.

After reading your source I think the reason is that you only use the fallbacks to determine which dict to load by remapping the request filename in Hyphenopoly_Loader., but do not use the fallbacks to determine the connection between elements and loaded dict in Hyphenopoly.js iself correctly.

Or am I missing something important here?

The plan is to decouple lang-Values from dictionary filenames to map CMS langs to specific hpb-files (to differentiate German in CMS content for countries, but not for the hyphenation algo).

**Comment by mnater** [comment]
Hi

Thanks for this kind words and the detailed issue report.

Things around fallsbacks seem to be a bit crooked…
I think your guess is right and there are other problems, too (e.g. case sensitiveness, where it shouldn't).

I'll look into it these days.

**Comment by OktarinTentakel** [comment]
Since we started working around this problem with server-side mapping and lang-overrides on the html element and such (what a headache):

Any news on this? :D
