### ISSUE TITLE
Use Selectors instead of classnames

### ISSUE THREAD

**Issue by mnater** [mnater/Hyphenopoly#42]
Currently Hyphenopoly uses single classnames to select elements to be hyphenated.
[L300:](https://github.com/mnater/Hyphenopoly/blob/master/Hyphenopoly.js#L300)
````javascript
const nl = w.document.querySelectorAll("." + cn);
````
Using fully featured CSS-Selectors would give more flexibility.

**Comment by OktarinTentakel** [comment]
+1

**Comment by mnater** [comment]
Implemented in https://github.com/mnater/Hyphenopoly/commit/9582d0f4e2874da96d654d984310f1879b69ab67

Needs documentation.

**Comment by mnater** [comment]
Doc: 
https://github.com/mnater/Hyphenopoly/wiki/Home/643db45bef7339e3fe55d21921aba93a855bba07
