### ISSUE TITLE
Make node-module sync

### ISSUE THREAD

**Issue by mnater** [mnater/Hyphenopoly#47]
Currently the node module `Hyphenopoly.module.js` returns promises. This is great but doesn't work well with existing scripts that in generally work synchronous.

The module is currently async because the files (`.wasm` and `.hpb` are loaded async and the WebAssembly-Module is instantiated async).

With `fs.readFileSync()` and `new WebAssembly.Instance()` there are sync (allthough not recommended) alternatives available.

**Comment by rotsee** [comment]
This is more or less possible with `await`, but it's hard (impossible?) to catch errors when using multiple require language codes. This works:

```
const hyphenator = hyphenopoly.config({
  "require": ["qqq"],
  "hyphen": "•",
})
let t
try  {
  t = await hyphenator.then(x => x("Alarmerande pingvinisflak"))
} catch(e) {
  console.log("No such language!")
}
console.log(t)
// 'No such language!'
// undefined
```

Also, this will work:

```
const hyphenator = hyphenopoly.config({
  "require": ["de", "fr"]
  "hyphen": "•",
})

let t
try  {
  t = await hyphenator.get("de").then(x => x("Alarmerandde pingvinisflak"))
} catch(e) { 
  console.log("No such language!")
}
// 'Alar•me•r•an•de ping•vi•nis•flak'
```

This, however, will _not_ work:
```
const hyphenator = hyphenopoly.config({
  "require": ["de", "qqq"]
  "hyphen": "•",
})

let t
try  {
  t = await hyphenator.get("de").then(x => x("Alarmerandde pingvinisflak"))
} catch(e) { 
  console.log("No such language!")
}
```

**Comment by mnater** [comment]
`await` is afaik just syntactic sugar for `Promise.then()` and not really async: `await`can only be used in `async function`.

But it's true: I'll have to find a way to catch errors if `Hyphenopoly.config()` returns a `Map` of promises.
