### ISSUE TITLE
dontHyphenateClass setup option

### ISSUE THREAD

**Issue by RLesur** [mnater/Hyphenopoly#48]
First of all, thanks for this awesome work! I love it!
I struggled with the `dontHyphenateClass` setup option.

Reading the [wiki section](https://github.com/mnater/Hyphenopoly/wiki/Setup#donthyphenateclass), I understood that the `dontHyphenateClass` can be modified (maybe I'm wrong). I did several tests and I didn't succeed to modify its default value. 

The `donthyphenate` class works perfectly well (even if I try to modify the `dontHyphenateClass` value).

Is there something I missed?

**Comment by mnater** [comment]
Hi

Thank for your kind words and thanks for reporting.
It's fixed in master and will be part of the next bugfix release.

Best regards,
Mathias

**Comment by RLesur** [comment]
Thanks a lot, Mathias!
