### ISSUE TITLE
use in react

### ISSUE THREAD

**Issue by kevinpursuing** [mnater/Hyphenopoly#49]
how i use in react?

**Comment by mnater** [comment]
What do you want to do?
Front-end or SSR or both?
What have you tried so far?

I don‘t know react very well. Exact answers (including code) to those questions could give me a good starting point…

**Comment by mnater** [comment]
Hope this helps:

https://github.com/mnater/Hyphenopoly/wiki/Hyphenators#use-case-hyphenopoly-in-react
