### ISSUE TITLE
Add removeHyphenationFromDocument

### ISSUE THREAD

**Issue by Imangazaliev** [mnater/Hyphenopoly#5]

**Comment by mnater** [comment]
Please provide a use case.
I try to keep hyphenopoly.js as small as possible…

**Comment by Imangazaliev** [comment]
I a'm using Hyphenator in my Android application (html book) when I need posibility to enable/disable hyphenation

**Comment by mnater** [comment]
This is Hyphenopoly.js not Hyphenator.js
Hyphenopoly.js doesn't cover your use case – so stick with Hyphenator.js where you can use [Hyphenator.toggleHyphenation()](https://github.com/mnater/Hyphenator/blob/wiki/en_PublicAPI.md#void-hyphenatortogglehyphenation) to remove hyphenation.
