### ISSUE TITLE
[2.7.0] Too many errors of type "Element with 'xy' found, but 'xy.hpb' not loaded. Check language tags!"

### ISSUE THREAD

**Issue by ReLater** [mnater/Hyphenopoly#56]
I have a simple HTML like this
```
<html lang="de-de" dir="ltr">
<head>
--- Some not relevant stuff here ---
<script>
var Hyphenopoly = {
 require: {
  "de-de": "Silbentrennungsalgorithmus"
 },
 fallbacks: {
  "de-de": "de"
 },
};
</script>
<script src="path/to/Hyphenopoly_Loader.js"></script>
</head>

<body class="hyphenate">

<header class="header" lang="la">
--- Some content here in some child tags---
</header>
<nav class="navigation" Lang="en-gb">
--- Some more content here in some more child tags ---
</nav>
<div class="whatever">
--- Lots of German content here in some child tags ---
</div>
</body>
</html>
```
- 1 attribute  lang="de-de" in HTML tag.
- And Just 1 attribute `lang="la"` at all.
- And just 1 attribute `lang="en-gb"` at all.
- The content is hyphenated but I get 7 + 15 = 22 error messages in the browser console. As far as I see for nearly any child tag.
- Yes, I know that I shall add these 2  languages to `required`, too.

#### Vivaldi browser ( a Chrome clone)

![04-02-_2019_02-21-56](https://user-images.githubusercontent.com/20780646/52185995-fa9c6d00-2824-11e9-9dd5-68fb2ee63bf9.jpg)

#### Chrome browser
- The same but messages are combined a little bit more human friendly.

#### Just questions. Just "nice to have".

- First question is if these messages shouldn't be just infos or warnings to avoid panicked users ;-)
- Second question is if you can find a solution to reduce the number of messages.

**Comment by mnater** [comment]
Thank you.
 
I think both can be done.

**Comment by mnater** [comment]
In bee6c9a7a782c64cbd5bddfee384912769431321 different levels (info/warning/error) are implemented in Hyphenopoly's "error"-event.

About reducing the number of messages:
While this could be achieved by creating a history of messages and only log new messages I decided to not implement this. I think this big number of messages reflects clearly that something in the setup is wrong. I think it's ok to emit the message for all (child-)elements that are marked to be hyphenated.

Doing `<body class="hyphenate">` isn't a great choice in most situations:

- hyphenating the whole body could lead to performance issues.
- many typographic manuals do not recommend to hyphenate headings and navigation but only text.

I'd recommend to only select elements that are really needed to be hyphenated. In your example:
````javascript
setup: {
        selectors: {
            ".whatever": {}
        }
    }
````

**Comment by ReLater** [comment]
Thanks for looking on it.

> Doing `<body class="hyphenate">` isn't a great choice in most situations

Yes, I know ;-) Users of my Joomla plugin see a fat warning when they configure the hyphenate and donthyphenate selectors. Some won't learn it or can live with it. Freedom of choice. 

Concerning messages: I have added an option to disable them in my plugin (with a description about advantages concerning  debugging). It uses a `handleEvent .... preventDefault()` in the background.
