### ISSUE TITLE
Feature request: Find out if a language tag is supported

### ISSUE THREAD

**Issue by rotsee** [mnater/Hyphenopoly#57]
It would be great if there was a way to find out what languages are supported, without having to resort to trying every possible language code to see if it throws an error or not.

Use case: If I have a language fallback chain like `no => nb => nn` (Norwegian, followed by the two official language varieties), or `en-ZA => en-GB => en` (South African English, followed by British English, followed by the general tag), it would be nice to be able to find out what language in the chain is the first to be supported.

**Comment by janschill** [comment]
Can't you just have a look into https://github.com/mnater/Hyphenopoly/tree/master/patterns?

**Comment by rotsee** [comment]
I guess, but that seems extremely awkward? I would end up with something like this:

```
const path = require("path")
const fs = require('fs')
const hyphenopoly = require("hyphenopoly")

// Find out where hyphenpoly was loaded from. Often, but not always ./node_modules/hyphenpoly
let hyphenopolyPath = require.resolve("hyphenopoly")
hyphenopolyPath = hyphenopolyPath.split(path.sep)
hyphenopolyPath.pop()

// Get a list of files in the patterns subdir
hyphenopolyPath.push("patterns")
hyphenopolyPath = hyphenopolyPath.join(path.sep)
let files = fs.readdirSync(hyphenopolyPath)

// Assume that every .hpb file represents one supported language tag
let supportedLanguageTags = file
	.filter(f => f.endsWith(".hpb"))
	.map(f => f.split(".")[0])
```

I can see a lot of problems with that:

 - Esoteric server environments, where this doesn't work as expected
 - Will break when you decided to rename `patterns` in a minor update
 - You have accidentally checked in a MacOS `.DS_Store` file in that dir. Things like that can and will happen again, but shouldn't break client code

I would rather then make a hard-coded list of languages to compare against, but that comes at the price of having to keep the list up to date with any updates to this lib...

**Comment by mnater** [comment]
Hi

Do you request this feature for the browser-script or for the node module (or both)?

I'm not sure if such language fallback chains would word correctly. E.g. your chain is `no => nb => nn` and the library has patterns for `nb` and for `nn`. If the text is annotated `no` and written in `nn` this could lead to wrong hyphenation. I'd prefer no hyphenation instead of wrong hyphenation…

**Comment by janschill** [comment]
Well, of course it would be good to have script test if the language is supported, but it takes not even a minute to check the folder and find out, in my humble opinion

**Comment by rotsee** [comment]
@mnater For the node module, sorry for being unclear.

@janschill Yes, but it would mean that I have to maintain a hard-coded list of currently supported language tags, as I can not expect my end users to look in a folder in a Github repo before entering a language.

@mnater Re the Norwegain fallback chain, `no` is considered a [macro language](https://iso639-3.sil.org/code/nor) in ISO 639, with `nb` and `nn` as individual varieties, but users and developers alike frequently use `no` (even Wikipedia [uses `no`, rather than `nb`](https://no.wikipedia.org/wiki/Portal:Forside)!). CLDR has the tags `no` and `nb` as symmetric fallbacks [at a distance of 1](https://www.unicode.org/cldr/charts/34/supplemental/language_matching.html), meaning that they are practically interchangeable, and the raw data file states that [no is normally taken as nb in content](http://unicode.org/repos/cldr/tags/latest/common/supplemental/languageInfo.xml) in a comment. But language fallback chains are of course highly depended on the what context they are used in. In my case, the consumer of the libraries I was thinking about including Hyphenopoly in, define fallback chains themselves (because I can't know what their exact needs are). This was just an example, but one that often appears in the wild.

**Comment by mnater** [comment]
Thanks for clarification
