### ISSUE TITLE
[2.7.0] Patterns loaded twice under some fallback circumstances.

### ISSUE THREAD

**Issue by ReLater** [mnater/Hyphenopoly#58]
Example: I've configured like follows for a page that uses `lang=en-us` and `lang=en-au`. There's a pattern `en-us.hpb` but no `en-au.hpb`. Thus I configured `en-us` as fallback pattern for it.

```
var Hyphenopoly = {
    "require": {
        "en-us": "supercalifragilisticexpialidocious",
        "en-au": "supercalifragilisticexpialidocious"
    },
    "fallbacks": {
        "en-au": "en-us"
    },
    "paths": {
        "patterndir": "/pathto/patterns/",
        "maindir": "/pathto2/hyphenopoly/"
    }
};
```

Inside console tab "Network" it looks like the en-us pattern is loaded twice(?):

![08-02-_2019_16-46-07](https://user-images.githubusercontent.com/20780646/52489031-8580bd00-2bc1-11e9-9d77-91670ca6425c.jpg)

**Comment by mnater** [comment]
Thanks

I was able to reproduce this issue.
