### ISSUE TITLE
Disable Fallback to Native

### ISSUE THREAD

**Issue by exophunk** [mnater/Hyphenopoly#6]
Is it possible to disable the fallback to native browser hyphenation? So hyphenopoly is always used?

Apparently, the native hyphenation rules of browsers are worse. At least for safari and german, I get much better results with your library.

**Comment by mnater** [comment]
Hi
If you want to force the usage of Hyphenopoly.js for a language write "FORCEHYPHENOPOLY" instead of the long word in the require block.
