### ISSUE TITLE
Chrome browser

### ISSUE THREAD

**Issue by RaedQumsieh** [mnater/Hyphenopoly#63]
I downloaded your code and started the example1.html. I noticed that the hyphenation isn't working under Chrome! Though it works fine under Edge and FireFox.

Chrome 72.0.3626.109
![screenshot 2019-02-19 17 21 54](https://user-images.githubusercontent.com/29050781/53031379-06b33c00-346d-11e9-8598-2eeada249888.png)

MS Edge:
![screenshot 2019-02-19 17 22 56](https://user-images.githubusercontent.com/29050781/53031435-2185b080-346d-11e9-9ed0-329618f789ce.png)

**Comment by mnater** [comment]
Are there any messages in the developer console?

**Comment by mnater** [comment]
Ah, now I noticed.
You'll have to load the example1.html over http or https from a server and not over the file:// scheme.

Hyphenopoly doesn't work on FF either if loaded over `file://`. Firefox supports CSS-hyphenation for all languages in the example. Thus, the hyphenation you see is not from Hyphenopoly but from Firefox...
