### ISSUE TITLE
Event when native hyphens are supported (was: forcing leftmin with word joiners U+2060)

### ISSUE THREAD

**Issue by masi** [mnater/Hyphenopoly#67]
On browser that do support hyphenation I want to enforce leftmin (maybe rightmin as well). I cannot set leftmin with CSS.

But in Firefox and Edge it is possible to use the word joiner (`&#x2060;`) to prevent breaking. It would be nice to have Hyphenoply add word joiners after the second character (and all the following if necessary) to have leftmin working for native hyphenation.

**Comment by mnater** [comment]
Hi

There's a CSS property called `hyphenate-limit-chars` that was once in CSS3 but got deferred to CSS4 (https://www.w3.org/TR/css-text-4/#hyphenate-char-limits). I don't know how the actual support looks like in current browsers.

I don't think that Hyphenopoly should add word joiners. Hyphenopoly is only loaded, when native hyphenation doesn't work and I'd like to keep Hyphenopoly_Loader as small as possible. I think this should be done by a specialized script.

If you need the full control over hyphenation and if you don't care about the load, you could enforce usage of Hyphenopoly: https://github.com/mnater/Hyphenopoly/wiki/Global-Hyphenopoly-Object#require

I'll close this for now.

Kind regards,
Mathias

**Comment by masi** [comment]
Ok, no problem. Is there any event triggered when Hyphenopoly is NOT loaded because of native support? This way I could hook up my own word-joiner-injection code only on browser with native support.

For now  have turned on Hyphenopoly for all browsers. All on my own thanks to the documentation.

Cheers,
Masi

**Comment by mnater** [comment]
There’s no such event. But good idea!
