### ISSUE TITLE
SyntaxError: Unexpected keyword 'const'.

### ISSUE THREAD

**Issue by tdeuling** [mnater/Hyphenopoly#72]
Hi,
we get the following Error in for example Safari/iOS v9.

```
Hyphenopoly_Loader.js
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
```
![Selection_259](https://user-images.githubusercontent.com/1298841/56377508-e1dc0a80-620a-11e9-96ef-bff14fcbcd90.png)

Whst could be the problem?

**Comment by mnater** [comment]
Hi

Hyphenopoly uses ES6 variable definitions (let and const) instead of the older `var` definitions.

Old iOS Safaris had a bug where const wasn‘t recognized in strict mode. This has been fixed in iOS 10.

If you really need support for legacy browsers use a transpiler like https://babeljs.io/
