### ISSUE TITLE
Loader looks for files in the wrong folder

### ISSUE THREAD

**Issue by plagasul** [mnater/Hyphenopoly#73]
Hello,
I am using hyphenopoly on a a Kirby cms installation.
At the moment the loader seems to look for files on ```http://localhost/website/Hyphenopoly/``` but the files are actually on ```http://localhost/website/assets/js/Hyphenopoly```

This is probably because Kirby handles its own routes internally but, is there any way to tell hyphenopoly where to look ?

Thank you

**Comment by ReLater** [comment]
Did you try `paths` already?
https://github.com/mnater/Hyphenopoly/wiki/Global-Hyphenopoly-Object#paths

e.g. I use
```
...
,
    "paths": {
        "patterndir": "/media/plg_system_hyphenateghsvs/js/hyphenopoly/patterns/",
        "maindir": "/media/plg_system_hyphenateghsvs/js/hyphenopoly/"
    },
...
```

**Comment by plagasul** [comment]
It worked using paths AND fixing folder permissions.
Perhaps it may be helpful for somebody else to note that although the loader was placed at ```/assets/js/hyphenopoly/```, it started searching for the other files at ```/``` (I assume this is kirby's routing doing) so I had to declare the paths like this:
```
paths: {
    patterndir: "assets/js/hyphenopoly/patterns/", //path to the directory of pattern files
    maindir: "assets/js/hyphenopoly/" //path to the directory where the other ressources are stored
}
```
Thanks

**Comment by plagasul** [comment]
I've reopened because it is not fixed as I thought.

The loader seems to be looking one folder UP from the actual page's location, which is puzzling.

If the page is at ```http://localhost/webdev/page/index.html``` 
Then it looks at ```http://localhost/webdev/Hyphenopoly```

If the page is at ```http://localhost/webdev/page/folder/index.html``` 
It looks at ```http://localhost/webdev/page/Hyphenopoly```

Is that just Kirby or hyphenopoly is designed to work like this?

Thank you

**Comment by plagasul** [comment]
Ok now I see how it works and I fixed it using Kirby's own method ``` $kirby->url('assets')``` and the paths option.
Thanks
