### ISSUE TITLE
Speed Hyphenopoly versus Hyphenator?

### ISSUE THREAD

**Issue by FrankConijn** [mnater/Hyphenopoly#74]
Not really an issue, but a for me important question: How do Hyphenopoly and Hyphenator compare when it comes to rendering speed? I want to use them only for browser hyphenation.

**Comment by mnater** [comment]
Hi

Thanks for this interesting question.

_First of all: please note that Hyphenator is no longer maintained._

Back to your question:
The answer is difficult.

__network requests__
Hyphenator can be run without the loader. So on a typical page (one language) only _two_ http requests are necessary (Hyphenopoly.js and the pattern file) – or three if you use the loader.
Hyphenopoly.js in contrast is always loaded by Hyphenopoly_Loader.js and needs the hyphenEngine (asm or wasm) and of course the pattern file. That's in total _four_ http requests.
On a network with high latency (i.e. mobile) Hyphenator may be faster (at least if you don't use http/2).

__bandwith/file size__
Hyphenopoly dropped some features that were included in Hyphenator but are no longer necessary in a modern web (e.g. support of frames, usage as bookmarklet, support for very old browsers) thus the file size of the main script is smaller (even if we add the 1kB of the hyphenEngine). The pattern files used by Hyphenopoly are binaries highly optimised for small sizes. But Hyphenopoly_Loader.js is bigger than Hyphenator_Loader.js.
If the loader decides not to load the main script and the pattern file Hyphenator wins. But if hyphenation needs to be done in JavaScript Hyphenopoly wins.

__execution__
Once the resources are loaded Hyphenopoly is almost twice as fast as Hyphenator.

__paint__
Upon checking browser support for CSS hyphenation Hyphenopoly does exactly one style calculation and one paint regardless of the number of languages to check while Hyphenator does one style calculation and one paint per language. This makes no difference if you only check one language.

__conclusion__
On a first view of a webpage (no cached resources) you'll have about the same speed when hyphenation is done by the script. On subsequent views (when resources are retrieved from the cache) Hyphenopoly is faster. But Hyphenopoly comes with a small penalty of a larger loader-script.

I hope this answers your question.
Kind regards,
Mathias

… and I'll have to invest some time in reducing the file-size of Hyphenopoly_Loader.js
