### ISSUE TITLE
Some selectores are not hyphenated

### ISSUE THREAD

**Issue by astridx** [mnater/Hyphenopoly#75]
I have a site where some selectors do not use JavaScript hyphenation.

Here is my code.
```
;
var Hyphenopoly= {
    require: {
        "de": "FORCEHYPHENOPOLY", "de-de": "FORCEHYPHENOPOLY"
    }
    ,
    fallbacks: {
        "de-de": "de"
    }
    ,
    paths: {
        patterndir: "/media/plg_system_aghyphenopoly/hyphenopoly/patterns/", maindir: "/media/plg_system_aghyphenopoly/hyphenopoly/"
    }
    ,
    setup: {
        defaultLanguage: "de",
        timeout: 1000,
        safeCopy: true,
        dontHyphenateClass: "donthyphenate",
        exceptions: [],
        selectors: {
            "html": {
                "compound": "all", "hyphen": "\u00ad", "minWordLength": "6", "leftmin": "3", "rightmin": "3", "orphanControl": "1"
            }
            ,
            "h3": {
                "compound": "all", "hyphen": "\u00ad", "minWordLength": "6", "leftmin": "3", "rightmin": "3", "orphanControl": "1"
            }
            ,
            "h2": {
                "compound": "all", "hyphen": "\u00ad", "minWordLength": "6", "leftmin": "3", "rightmin": "3", "orphanControl": "1"
            }
            ,
            "h1": {
                "compound": "all", "hyphen": "\u00ad", "minWordLength": "6", "leftmin": "3", "rightmin": "3", "orphanControl": "1"
            }
        }
    }
}

;
```

You can see the issue on this test page: https://awo.astrid-guenther.de/datenschutzerklaerung
or on http://190409y73r6bzqcxxiq.wh.routing.zone/index.php/datenschutzerklaerung. The text "Datenschutzerklärung" is not hyphenated on old devices.
Apart form that the hyphenation works.

Am I doing something wrong?

**Comment by mnater** [comment]
Hi

`orphanControl` is expected to be of type `Number` (as well as `minWordLength`, `leftmin` and `rightmin`:

````javascript
"compound": "all", //String
"hyphen": "\u00ad",
"minWordLength": 6, //Number
"leftmin": 3,
"rightmin": 3,
"orphanControl": 1
````

That should solve the issue.

Further suggestions:
- `"hyphen"` defaults to the soft hyphen. No need of setting this explicitly.
- Don't use `"html"` as selector. Use `"body"` if you want to hyphenate the all content. (Using `"html"` unnecessarily processes the whole document including all content in the `<head>` wich slows down everything.)
- If you select a parent tag, all it's descendants are hyphenated with the same settings. So no need to select `"h1"`, `"h2"` and `"h3"` if you selected `"html"` (or `"body"`) unless you need other settings.

Kind regards,
Mathias

**Comment by astridx** [comment]
Sorry for replying so late. Today I came to look at your tip. Thank you for the detailed information and the hint. Now everything works.
