### ISSUE TITLE
Supply a long word for each language

### ISSUE THREAD

**Issue by henk23** [mnater/Hyphenopoly#79]
Just a suggestion, let's collect a list of long words for all the supplied languages in the patterns directory.
I for one am only fluent in two languages and don't really have a clue what to put into the require object for the other eight languages my client's website supports.

Here's a start, collected from the wikipedia list of longest words:

```
"de": "Bundespräsidentenstichwahlwiederholungsverschiebung",
"en": "pneumonoultramicroscopicsilicovolcanoconiosis",
"nl": "Kindercarnavalsoptochtvoorbereidingswerkzaamhedenplan",
"da": "speciallægepraksisplanlægningsstabiliseringsperiode",
"sv": "Realisationsvinstbeskattning",
"fi": "lentokonesuihkuturbiinimoottoriapumekaanikkoaliupseerioppilas",
"cs": "Nejneobhospodařovávatelnějšímu",
"pl": "dziewięćdziesięciokilkuletniemu",
"hu": "megszentségteleníthetetlen",
"it": "precipitevolissimevolmente",
"fr": "hippopotomonstrosesquippedaliophobie",
```

**Comment by mnater** [comment]
Great idea!
Shouldn't we make this a page in the project's wiki?

**Comment by henk23** [comment]
I was thinking maybe rather 'hard code' these words somewhere so the user does not have to specify this at all. Ideally the config could look like this:
```
var Hyphenopoly = {
  require: ['de', 'it']
}
```
Hyphenator_Loader.js can then feature test the browser for CSS-hyphens support _automagically_. 🌈

**Comment by mnater** [comment]
Yep, technically possible. But it comes with the cost of ~1kb larger file size.
I prefer to keep the loader-script as small as possible.

But I can imagine a tool similar to the [mergeAndPack-tool in Hyphenator](http://mnater.github.io/Hyphenator/mergeAndPack.html) that automises this step (and merges the configuration part with the loader script). With this we could gain the ease-of-use you propose but keep the file sizes as small as possible.

**Comment by henk23** [comment]
Ah, I see, that makes sense and sounds good. :)

**Comment by mnater** [comment]
Some ideas:

A) Tool like mergeAndPack

- [-] there are many options and it's almost impossible to test correctness of all possible output of such a tool
- [-] setting up such a tool is boring
- [+] nice and easy to use
- [+] 4 resources (Loader with config, Hyphenoply, Engine and pattern)
- [-] two sources of information about config to maintain (or delete wiki pages)

B) A tool that just helps to setup basic settings (i.e. `require` with prefilled long words). All other settings have to be entered/uploaded in a textfield in JSON format and are checked for corectness of types and values/value ranges.
- [+] only basic options need to be programmed and they can be tested
- [+] using or creating a kind of a linter is interesting and challenging
- [+] 4 resources (Loader with config, Hyphenoply, Engine and pattern)
- [-] not as easy to use (involves coding)
- [-] options need to be looked up in wiki

C) leave everithing as it is and give a list of possible long names in wiki
- [-] not a easy to use (involves coding)
- [-] 5 resources (config, Loader, Hyphenoply, Engine and pattern)
- [-] corectness of config isn't checked
- [+] no additional code to maintain
- [+] focus my work on main scripts

Todo:
- check if a tool for A) already exists
    -> [https://jsonforms.io](https://jsonforms.io)
    -> [https://github.com/jsonform/jsonform](https://github.com/jsonform/jsonform)

- check if linter for B) exists

**Comment by mnater** [comment]
I‘ve tried jsonform(s). 
There‘s no fun. I‘ll stick with option C) for now.
