### ISSUE TITLE
minor issue with language codes that aren't region specific

### ISSUE THREAD

**Issue by VAggrippino** [mnater/Hyphenopoly#8]
Many general examples specify an `html` tag with a `lang` property like `<html lang="en">`, but Hyphenopoly uses region-specific pattern files like en-us and en-gb.

So, it doesn't work if I have code that looks something like this:

```html
<html lang="en">
...
  <script>
    var Hyphenopoly = {
      require: {
        'en': 'automatically'
      },
      paths: {
        patterndir: "js/patterns/",
        maindir: "js/"
      },
      setup: {
        classnames: {
          'hyphenate': {},
          'description': {}
        }
      }
    };
  </script>
  <script src="js/Hyphenopoly_Loader.js"></script>
```

There are a thousand ways you could handle this, including just a note in the documentation to be aware of it. After I realized what was wrong, I just changed the `lang` property on my `html` tag and in the `require` object property.

Thank you.

**Comment by mnater** [comment]
Thank you
