### ISSUE TITLE
docs/index.md. Dead links?

### ISSUE THREAD

**Issue by ReLater** [mnater/Hyphenopoly#83]
Maybe I just don't understand correctly how to use the new docs structure (since 3.1.1)?

When I open https://github.com/mnater/Hyphenopoly/blob/master/docs/index.md all links are "dead" because of missing `*.md` in links.

**Comment by mnater** [comment]
Hi

Thanks for reporting.
You can access documentation at http://mnater.github.io/Hyphenopoly/ until this is fixed.

**Comment by mnater** [comment]
Fixed: https://github.com/mnater/Hyphenopoly/commit/734edf42e9b4d26852ffee05cf486005f4980261
