### ISSUE TITLE
Hyphenate without file being served over http/s?

### ISSUE THREAD

**Issue by jportella93** [mnater/Hyphenopoly#84]
Hi! First of all, thanks for the great package, it's a live saver :)

So I'm trying to hyphenate a local html file that doesn't get served over http/s. The problem is that the Loader tries to load the pattern file using Fetch, so it fails to load a `file:///`. 

I get the following error:
```
Hyphenopoly_Loader.js:406 Fetch API cannot load file:///<path-to-file...>/patterns/de.hpb. URL scheme must be "http" or "https" for CORS request.
```

Is there any workaround for this? I'm just trying to load this `.html` with Headless Chrome in order to convert it to `.pdf`, so I'd like to keep this lib locally.

Thanks~

**Comment by jportella93** [comment]
I'm being able to get the files when I serve them over http with a local server and specifying the paths in
```javascript
    <script>
      var Hyphenopoly = {
        require: {
            "de": "FORCEHYPHENOPOLY",
        },
        setup: {
            selectors: {
                ".hyphenation-container": {
                  minWordLength: 4
                }
            }
        },
        paths: {
          "patterndir": "http://127.0.0.1:5500/<...>/libs/hyphenopoly/patterns/",
          "maindir": "http://127.0.0.1:5500/<...>/libs/hyphenopoly/"
        }
      };
    </script>
```
As the files are just being served as they are, maybe it would be a good idea to have a cdn or some link to just put in there to avoid running a local server?

**Comment by mnater** [comment]
Hi

There's no workaround in Hyphenopoly_Loader.js, which is intended to run as a polyfill on websites.

For that use case (converting to pdf) you could also use the [node module](https://mnater.github.io/Hyphenopoly/Node-Module.html) which loads the files using the "fs"-module (you'll need node and do some more coding, though).

Using a CDN would be the fastest way. Hyphenopoly is currently available on the following CDNs:
https://unpkg.com/hyphenopoly@3.1.2/
https://bundle.run/hyphenopoly@3.1.2
https://cdn.jsdelivr.net/npm/hyphenopoly@3.1.2/
and [waiting for approval](https://github.com/cdnjs/cdnjs/pull/13323) in cdnjs.

Regards, Mathias

**Comment by jportella93** [comment]
cdn fixed it! 👍  

```javascript
    <script>
      var Hyphenopoly = {
        require: {
            "de": "FORCEHYPHENOPOLY",
        },
        setup: {
            selectors: {
                ".hyphenation-container": {
                  minWordLength: 4
                }
            }
        },
        paths: {
          "patterndir": "https://unpkg.com/hyphenopoly@3.1.2/patterns/",
          "maindir": "https://unpkg.com/hyphenopoly@3.1.2/"
        }
      };
    </script>
    <script src="https://unpkg.com/hyphenopoly@3.1.2/Hyphenopoly_Loader.js"></script>
```

**Comment by janschreier** [comment]
Hi there,
i had the requirement to have all data locally so refering to a CDN  was no option for me.  I solved it by using XMLHttpRequest insteead of fetch. In the loader you need this new function to `Hyphenopoly_Loader.js`:


```
 //strongly inspired by from https://gitlab.pagedmedia.org/tools/pagedjs/blob/master/src/utils/request.js
async function request(url, options = {}) {
	return new Promise(function (resolve, reject) {
		let request = new XMLHttpRequest();
		request.responseType = "arraybuffer";
		request.open(options.method || "get", url, true);

		for (let i in options.headers) {
			request.setRequestHeader(i, options.headers[i]);
		}

		request.withCredentials = options.credentials === "include";

		request.onload = () => {
			// Chrome returns a status code of 0 for local files
			const status = request.status === 0 && url.startsWith("file://") ? 200 : request.status;
			resolve(new Response(request.response, { status }));
		};

		request.onerror = reject;

		request.send(options.body || null);
	});
}
```
and in `loadhyphenEngine` replace `w.fetch` with `request`.

If interesting, I can create a PR for this. Otherwise I hope it helps others.
