### ISSUE TITLE
Hyphenopoly Loader fails on Firefox 60.x ESR with Client SSL certificate

### ISSUE THREAD

**Issue by bfrb** [mnater/Hyphenopoly#85]
Given that
* an application is served by a server which requires an client SSL certificate
and
* the browser being used to load the app is FireFox 60.x ESR
when Hyphenopoly_Loader.js uses window.fetch to load files then the request is answered with 403 forbidden.

The solution for me was to follow the one accepted over here: https://stackoverflow.com/questions/39417232/fetch-fails-in-firefox-with-ssl-client-authentication

With that local fix to Hyphenopoly_Loader.js the request issued via window.fetch is accepted by the server.

**Comment by mnater** [comment]
This is now configurable: https://github.com/mnater/Hyphenopoly/commit/1c68431ff0a61ddae0de20a2c14363fcd914b1ed
