### ISSUE TITLE
Is there any way to exclude some words from being hyphenated ?

### ISSUE THREAD

**Issue by dev-sabbir** [mnater/Hyphenopoly#86]
Hi,
I was thinking if there is any way you can exclude some specific words i.e. Brand name etc from being hyphenated in hyphenopoly configuration.Is there any existing configuration?
Thanks.

**Comment by mnater** [comment]
https://mnater.github.io/Hyphenopoly/Setup.html#exceptions
or
https://mnater.github.io/Hyphenopoly/Setup.html#donthyphenateclass

**Comment by dev-sabbir** [comment]
Thank you @mnater . Sorry I should be the one to close this issue.
