### ISSUE TITLE
Don't hyphenate Capitalized words

### ISSUE THREAD

**Issue by mnater** [mnater/Hyphenopoly#91]
There has been a Note added to the [css3-text editors draft](https://drafts.csswg.org/css-text-3/#hyphenation-opportunity) saying:

> Note: In some languages (such as English but not German), it may appropriate to avoid having hyphenation opportunities in mixed case words, as those may indicate proper nouns. This type of heuristic is however not mandated by this specification, as is up to the User Agent and its language-specific hyphenation resource.

(See discussion: https://github.com/w3c/csswg-drafts/issues/3927)

FF 68 [implemented this](https://bugzilla.mozilla.org/show_bug.cgi?id=1550532). And there are corresponging bug reports for [webkit](https://bugs.webkit.org/show_bug.cgi?id=197889) and [chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=963039&can=2&q=hyphen%20proper%20nouns).

I think avoiding hyphenation in all mixed cased words is not a good heuristic because it inhibits hyphenation of words at the beginning of a sentence, too. IMHO the author of the text should either add some markup to prevent hyphenation of proper nouns or add these words to the exception list.

Nevertheless Hyphenopoly should have an opt-in to enable this simple heuristic (or even “Capitalized words, except in German, and except after periods, unless we saw it capitalized not after a period”) to prevent hyphenation of mixed cased words.

Looks like an interesting problem to detect such words…

**Comment by HeikkiYlipaavalniemi** [comment]
This would be really good to be able to control also for words which are starting a sentence with a capital letter.

Both Finnish and Swedish languages can have really long words and in a mobile layout they can easily go over the screen width if they are starting a sentence. Either it will just wrap to the next line without hyphenation or break the layout.
