### ISSUE TITLE
Requests for pattern files (*.wasm) fail when Access-Control-Allow-Origin CORS header is "*"

### ISSUE THREAD

**Issue by jefferyto** [mnater/Hyphenopoly#98]
cdnjs recently merged Hyphenopoly (cdnjs/cdnjs#13323) and made it available (cdnjs/cdnjs#13759) so I thought I would try it out.

When I used the browser example from the readme with `"FORCEHYPHENOPOLY"`, this is the error message I see (one for each pattern file) in the Firefox console:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://cdnjs.cloudflare.com/ajax/libs/hyphenopoly/4.1.0/patterns/en-us.wasm’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).
```

I've tried this using Chrome and with CDN links from UNPKG and jsDelivr and I get the same results.

The "Learn More" link next to the error message leads to https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials, which explains that when the `Access-Control-Allow-Origin` CORS header is `*` (which cdnjs sets), the `credentials` option of a fetch request must be set to `omit` for the request to be allowed.

Currently in Hyphenopoly_Loader.js, the `credentials` option is [set](https://github.com/mnater/Hyphenopoly/blob/v4.1.0/Hyphenopoly_Loader.js#L273) to `include`.

I can see how `include` or `same-origin` would make sense for most custom deployments, but it doesn't appear to be compatible with CDNs (or other servers with `Access-Control-Allow-Origin` set to `*`). Perhaps the `credentials` option can be made configurable?

**Comment by mnater** [comment]
Hi

>Perhaps the credentials option can be made configurable?

Absolutely! Thanks for reporting - I wouldn't have found this.

**Comment by mnater** [comment]
fixed in https://github.com/mnater/Hyphenopoly/commit/a1a44574b242e35147697284c09a9fb5d07c181a
